"""Practice hints and unique daily sessions

Revision ID: 6868b87d1af0
Revises: d986b91d3dc7
Create Date: 2026-09-29 04:20:25.803667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6868b87d1af0'
down_revision = 'd986b91d3dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_key', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_attempt_daily_key', ['daily_key'])

    with op.batch_alter_table('attempt_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hints_used', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_question', schema=None) as batch_op:
        batch_op.drop_column('hints_used')

    with op.batch_alter_table('attempt', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('uq_attempt_daily_key', type_='unique')
        batch_op.drop_column('daily_key')

    # ### end Alembic commands ###
