import uuid
from datetime import datetime, timezone
from flask_login import UserMixin
from app.extensions import db

def now(): return datetime.now(timezone.utc).replace(tzinfo=None)
def uid(): return str(uuid.uuid4())

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(254), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    role = db.Column(db.String(20), default='student', nullable=False)
    enabled = db.Column(db.Boolean, default=True, nullable=False)
    timezone = db.Column(db.String(64), default='UTC')
    interests = db.Column(db.Text, default='')
    @property
    def is_active(self): return self.enabled

class ResetToken(db.Model):
    id = db.Column(db.String(64), primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    expires = db.Column(db.DateTime, nullable=False)
    used = db.Column(db.Boolean, default=False)

class ExecutionProfile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    language_id = db.Column(db.Integer, nullable=False)
    version = db.Column(db.String(80), nullable=False)
    enabled = db.Column(db.Boolean, default=False)

class Course(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), nullable=False)
    slug = db.Column(db.String(150), unique=True, nullable=False)
    description = db.Column(db.Text, default='')
    objectives = db.Column(db.Text, default='')
    prerequisites = db.Column(db.Text, default='None')
    category = db.Column(db.String(30), default='language')
    level = db.Column(db.String(30), default='Beginner')
    status = db.Column(db.String(20), default='draft')
    version = db.Column(db.String(30), default='1.0')
    reviewed = db.Column(db.String(30), default='')
    references = db.Column(db.Text, default='')
    profile_id = db.Column(db.ForeignKey('execution_profile.id'))
    profile = db.relationship(ExecutionProfile)
    rules = db.Column(db.JSON, default=lambda: {'weights': {'concept':1,'error':2,'output':2,'code':5}, 'seconds':{'concept':45,'error':90,'output':60,'code':240},'pass':70})
    modules = db.relationship('Module', order_by='Module.position', backref='course')

class Module(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    course_id = db.Column(db.ForeignKey('course.id'), nullable=False)
    title = db.Column(db.String(150), nullable=False)
    position = db.Column(db.Integer, default=0)
    topics = db.relationship('Topic', order_by='Topic.position', backref='module')
class Topic(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    module_id = db.Column(db.ForeignKey('module.id'), nullable=False)
    title = db.Column(db.String(150), nullable=False)
    position = db.Column(db.Integer, default=0)
    lessons = db.relationship('Lesson', order_by='Lesson.position', backref='topic')
class Lesson(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    topic_id = db.Column(db.ForeignKey('topic.id'), nullable=False)
    title = db.Column(db.String(150), nullable=False)
    objectives = db.Column(db.Text, default='')
    body = db.Column(db.Text, default='')
    code = db.Column(db.Text, default='')
    mistakes = db.Column(db.Text, default='')
    exercise = db.Column(db.Text, default='')
    position = db.Column(db.Integer, default=0)
    status = db.Column(db.String(20), default='published')
class Enrollment(db.Model):
    __table_args__ = (db.UniqueConstraint('user_id','course_id'),)
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    course_id = db.Column(db.ForeignKey('course.id'), nullable=False)
    course = db.relationship(Course)
class Progress(db.Model):
    __table_args__ = (db.UniqueConstraint('user_id','lesson_id'),)
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    lesson_id = db.Column(db.ForeignKey('lesson.id'), nullable=False)
    completed = db.Column(db.DateTime, default=now)
class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    course_id = db.Column(db.ForeignKey('course.id'), nullable=False)
    topic_id = db.Column(db.ForeignKey('topic.id'), nullable=False)
    version = db.Column(db.Integer, default=1)
    state = db.Column(db.String(20), default='draft')
    fingerprint = db.Column(db.String(64), unique=True, nullable=False)
    difficulty = db.Column(db.String(20), default='beginner')
    category = db.Column(db.String(20), nullable=False)
    content = db.Column(db.JSON, nullable=False)
    topic = db.relationship(Topic)
class Attempt(db.Model):
    id = db.Column(db.String(36), primary_key=True, default=uid)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False, index=True)
    course_id = db.Column(db.ForeignKey('course.id'), nullable=False)
    course = db.relationship(Course)
    user = db.relationship(User)
    mode = db.Column(db.String(20), nullable=False)
    daily_key = db.Column(db.String(100), unique=True)
    status = db.Column(db.String(20), default='ready', index=True)
    rules = db.Column(db.JSON, nullable=False)
    started_at = db.Column(db.DateTime)
    expires_at = db.Column(db.DateTime, index=True)
    submitted_at = db.Column(db.DateTime)
    grading_started = db.Column(db.DateTime)
    earned = db.Column(db.Float, default=0)
    total = db.Column(db.Float, default=0)
    analysis = db.Column(db.Text)
    questions = db.relationship('AttemptQuestion', order_by='AttemptQuestion.position', backref='attempt')
class AttemptQuestion(db.Model):
    __table_args__ = (db.UniqueConstraint('attempt_id','position'),)
    id = db.Column(db.Integer, primary_key=True)
    attempt_id = db.Column(db.ForeignKey('attempt.id'), nullable=False)
    question_id = db.Column(db.ForeignKey('question.id'), nullable=False)
    topic_id = db.Column(db.ForeignKey('topic.id'), nullable=False)
    position = db.Column(db.Integer, nullable=False)
    snapshot = db.Column(db.JSON, nullable=False)
    points = db.Column(db.Float, nullable=False)
    answer = db.Column(db.Text, default='')
    flagged = db.Column(db.Boolean, default=False)
    hints_used = db.Column(db.Integer, default=0)
    earned = db.Column(db.Float)
    outcome = db.Column(db.JSON)
class Certificate(db.Model):
    id = db.Column(db.String(36), primary_key=True, default=uid)
    attempt_id = db.Column(db.ForeignKey('attempt.id'), unique=True, nullable=False)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    snapshot = db.Column(db.JSON, nullable=False)
    status = db.Column(db.String(20), default='valid')
    issued = db.Column(db.DateTime, default=now)
class Report(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.ForeignKey('question.id'), nullable=False)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    reason = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(20), default='open')
class Audit(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'))
    action = db.Column(db.String(200), nullable=False)
    created = db.Column(db.DateTime, default=now)
class Job(db.Model):
    id = db.Column(db.String(36), primary_key=True, default=uid)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    kind = db.Column(db.String(30), nullable=False)
    state = db.Column(db.String(30), default='pending')
    payload = db.Column(db.JSON, default=dict)
    message = db.Column(db.Text, default='')
    created = db.Column(db.DateTime, default=now)

class Resource(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(150),nullable=False)
    description = db.Column(db.Text,default='')
    url = db.Column(db.String(1000),nullable=False)
    category = db.Column(db.String(100),default='Documentation')
    status = db.Column(db.String(20),default='draft')
    position = db.Column(db.Integer,default=0)

class Category(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(100),nullable=False)
    slug = db.Column(db.String(100),unique=True,nullable=False)
    description = db.Column(db.Text,default='')
